/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/monster-pipeline/scene.gltf --types 
Author: VRC-IW (https://sketchfab.com/VRC-IW)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/monster-energy-pipeline-punch-355ml-jpn-64c92f3d7bfb40c78c6cff9f01d666e5
Title: Monster Energy Pipeline Punch 355ml JPN
*/

import * as THREE from 'three'
import React,{JSX, useRef} from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useFrame } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
  }
  materials: {
    Material_25: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationAction[]
}




export function MonsterPipeline(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/monster-pipeline/scene.gltf') as unknown as GLTFResult

  const monsterRef = useRef<JSX.IntrinsicElements['group']>(null!)

  useFrame((state,delta) =>{
      if (monsterRef.current) {
        (monsterRef.current.rotation as THREE.Euler).y += Math.PI * delta * 0.2
      }
  })
  return (
    <group {...props} dispose={null} ref={monsterRef} >
      <mesh geometry={nodes.Object_4.geometry} material={materials.Material_25} rotation={[0, 0, 0]}/>
    </group>
  )
}

useGLTF.preload('/models/monster-pipeline/scene.gltf')
